src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[UniqueEntity('titre' ,"Il existe déjà un article possedant ce titre")]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 5,minMessage: "Le titre doit comporter 5 caractères")]

    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Categorie $categorie = null;

    #[ORM\OneToMany(mappedBy: 'article_id', targetEntity: Commentaire::class)]
    private Collection $commentaires;

    #[ORM\Column]
    private ?bool $isPublie = null;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setArticleId($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticleId() === $this) {
                $commentaire->setArticleId(null);
            }
        }

        return $this;
    }

    public function isIsPublie(): ?bool
    {
        return $this->isPublie;
    }

    public function setIsPublie(bool $isPublie): self
    {
        $this->isPublie = $isPublie;

        return $this;
    }


}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Utilisateur $utilisateur_id = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUtilisateurId(): ?Utilisateur
    {
        return $this->utilisateur_id;
    }

    public function setUtilisateurId(?Utilisateur $utilisateur_id): self
    {
        $this->utilisateur_id = $utilisateur_id;

        return $this;
    }

    public function getArticleId(): ?Article
    {
        return $this->article_id;
    }

    public function setArticleId(?Article $article_id): self
    {
        $this->article_id = $article_id;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Categorie;
use Doctrine\ORM\Query\Expr\Select;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre',TextType::class)
            ->add('contenu',CKEditorType::class ,[
                'config'=>[
                    'uiColor'=>'theo vuillemin',
                ]
            ])
            ->add('categorie',EntityType::class,[
                'class'=>Categorie::class,
                'choice_label'=>"titre",
                'required'=>false,
                'placeholder'=>"aucune catégorie"
            ])
            ->add('isPublie',CheckboxType::class,[
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Commentaire;
use App\Entity\Utilisateur;
use App\Form\ArticleType;
use App\Form\CommentaireType;
use App\Repository\ArticleRepository;
use App\Repository\CategorieRepository;
use App\Repository\CommentaireRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class ArticleController extends AbstractController
{
    private ArticleRepository $articleRepository;
    private CommentaireRepository $commentaireRepository;
    private UtilisateurRepository $utilisateurRepository;


    public function __construct(ArticleRepository $articleRepository, CommentaireRepository $commentaireRepository, UtilisateurRepository $utilisateurRepository)
    {
        $this->articleRepository = $articleRepository;
        $this->commentaireRepository = $commentaireRepository;
        $this->utilisateurRepository = $utilisateurRepository;

    }

    #[Route('/articles', name: 'app_article')]
    // à l'appel de la methode, symfony vas creer un objet de la classe ArticleRepository et le passer en parametre de la methode
        // mecanisme : INJECTION DE DEPENDANCES
    public function getArticles(PaginatorInterface $paginator, Request $request): Response
    {
        // recuperer les infos dans la base de donnees
        // le controleur fais appel au modele (classe du modele) afin de recuperer la liste des articles
        // $repository = new ArticleRepository();

        //mise en place de la pagination

        $articles = $paginator->paginate(
            $this->articleRepository->findBy(["isPublie" => true], ['createdAt' => 'DESC'],),
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('article/index.html.twig', [
            "articles" => $articles
        ]);
    }

    #[Route('/articles/{slug}', name: 'app_article_slug', methods: ['GET', 'POST'])]
    public function getArticle(SluggerInterface $slugger, Request $request, $slug): Response
    {
        // recuperer les infos dans la base de donnees
        // le controleur fais appel au modele (classe du modele) afin de recuperer la liste des articles
        // $repository = new ArticleRepository();
        $commentaire = new Commentaire();
        $formCommentaire = $this->createForm(CommentaireType::class, $commentaire);
        $formCommentaire->handleRequest($request);
        if ($formCommentaire->isSubmitted() && $formCommentaire->isValid()) {
            $commentaire->setUtilisateurId($this->utilisateurRepository->findOneBy(['pseudo' => $formCommentaire->get('pseudo')->addError(new FormError("le pseudo n'existe pas"))->getData()]))
                ->setArticleId($this->articleRepository->findOneBy(["slug" => $slug]))
                ->setCreatedAt(new \DateTime());
            //inserer l'article dans la base de donnée
            $this->commentaireRepository->add($commentaire, true);
            //return $this->redirectToRoute('app_article_slug',['slug'=>$slug]);
        }

        return $this->renderForm('article/contenue_article.html.twig', [
            "article" => $this->articleRepository->findOneBy(["slug" => $slug]),
            "commentaires" => $this->commentaireRepository->findBy(["article_id" => $this->articleRepository->findBy(["slug" => $slug])]),
            "formCommentaire" => $formCommentaire
        ]);
    }


    #[Route('/articles/nouveau', name: 'app_article_nouveau', methods: ['GET', 'POST'], priority: 1)]
    public function insert(SluggerInterface $slugger, Request $request): Response
    {
        $article = new Article();

        //creation du formulaire
        $formArticle = $this->createForm(ArticleType::class, $article);

        // reconnaitre si le formulaire a ete soumis ou pas
        $formArticle->handleRequest($request);
        // est ce que le formulaire a ete soumis
        if ($formArticle->isSubmitted() && $formArticle->isValid()) {
            $article->setSlug($slugger->slug($article->getTitre())->lower())
                ->setCreatedAt(new \DateTime());
            //inserer l'article dans la base de données
            $this->articleRepository->add($article, true);
            return $this->redirectToRoute('app_article');
        }

        //appel de la vue twig permettant d'afficher le formulaire


        return $this->renderForm('article/nouveau.html.twig', [
            "formArticle" => $formArticle
        ]);


        /*$article->setTitre('Nouvel Article 2')->setContenu("Contenu de l'Article 2")->setSlug($slugger->slug($article->getTitre())->lower())->setCreatedAt(new \DateTime());
        //symfony 6 seulement
        $this->articleRepository->add($article,true);

        return $this->redirectToRoute("app_article"); */

    }

    #[Route('/articles/modifie:{slug}', name: 'app_articles_modifier_slug', methods: ['GET' , 'POST'] , priority: 1)]

// A l'appel de la méthode symfony va créer un objet de la classe ArticleRepossitory
        // et le passer en paramètre de la méthode
        // Mécanisme : INJECTION DE DEPENDANCES
    public function update(SluggerInterface $slugger, Request $request,$slug): Response
    {
        $article = $this->articleRepository->findOneBy(["slug" => $slug]);
        // Création du formulaire
        $formArticle = $this->createForm(ArticleType::class, $article);

        // Reconnaître si le formulaire a été soumis ou pas
        $formArticle->handleRequest($request);
        // Est-ce que le formulaire a été soumis
        if ($formArticle->isSubmitted() && $formArticle->isValid()) {
            $article->setSlug($slugger->slug($article->getTitre())->lower());


            $this->articleRepository->add($article, true);
            return $this->redirectToRoute("app_article");
        }

        // Appel de le vue twig permettant d'afficher le formulaire
        return $this->renderForm('article/modifier.html.twig', [
                'formArticle' => $formArticle,
                'article' => $article
            ]
        );
    }
}

templates/article/contenue_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contenu Article{% endblock %}

{% block body %}
    <div class="container">
        <h1 >{{ article.titre }}</h1>
        {% if article.categorie %}
        <a class="btn btn-secondary " href="{{ path('app_categorie_slug', { slug : article.categorie.slug}) }}" role="button">{{ article.categorie.titre }}
            </a>
        {% else %}
        <p>Pas de catégorie</p>
        {% endif %}
        <div>
            <p>{{ article.contenu | raw }}</p>
            <a class="btn btn-secondary " href="{{ path('app_articles_modifier_slug', { slug : article.slug}) }}" role="button">Modifier l'article
            </a>
        </div>
        {% if article.commentaires.count >1 %}
        <h2>{{ article.commentaires.count }} Commentaires</h2>
        {%else %}
        <h2>{{ article.commentaires.count }} Commentaire</h2>
        {% endif %}

        {{ form_start(formCommentaire) }}
        {{ form_row(formCommentaire.contenu,{
            'label' : "commenter" ,
            'attr' :{'placeholder' : "ecrire un commentaire"
            },
            'value' :'',
        }) }}
        {{ form_row(formCommentaire.pseudo ,{
            'value' : '',
            'label ' : "pseudo" ,

        }) }}
        <input type="submit" class="btn btn-primary" value="ajouter">
        {{ form_end(formCommentaire) }}


        {% if commentaires %}
            {% for commentaire in commentaires %}
                {% if commentaire.utilisateurId %}
                <h3>{{ commentaire.utilisateurId.pseudo }} </h3><p>({{ commentaire.createdAt | date("d/m/Y") }})</p>
                {% else %}
                <h3>Anonyme </h3><p>({{ commentaire.createdAt | date("d/m/Y") }})</p>
                {%  endif %}
                <p>{{ commentaire.contenu }}</p>
            {% endfor %}
        {% else %}
            <p>Aucun commentaire pour le moment</p>
        {% endif %}
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block body %}
    <div class="container">
    <h1 >Liste des articles</h1>
        <a href="{{ path('app_article_nouveau') }}" class="btn btn-primary mb-3">Créer un article</a>
    <ul>
        {% for article in articles %}
            <li><a href="{{ path('app_article_slug', { slug : article.slug}) }}">{{ article.Titre() }} </a>{{ article.createdAt |date("m/d/Y") }}</li>
        {% endfor %}
    </ul>
    </div>
    <div class="navigation d-flex justify-content-center">
        {{ knp_pagination_render(articles) }}
    </div>
{% endblock %}

templates/article/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'article{% endblock %}


{% block body %}
    <h1>Modification d'un article</h1>
    {{ form_start(formArticle) }}
    {{ form_row(formArticle.titre, {
        'label' : 'titre article',
        'attr' : {
            'placeholder' : "Veuillez saisir le titre de l'article"
        },
        'help' : "le titre doit contenir au moins 5 caractères"
    }) }}

    {{ form_label(formArticle.contenu,"Contenu de l'article" , {
        'label_attr' : {
            'class' : 'text-warning'
        }
    })}}

    {{ form_widget(formArticle.contenu, {
        'attr' : {
            'placeholder' : "Veuillez saisir un contenu"
        },
    })}}
    {{ form_help(formArticle.contenu , {
        'help' : "le contenu doit contenir au mois 36 caractères"
    }) }}
    {{ form_row(formArticle.categorie) }}
    {{ form_row(formArticle.isPublie ,{
        'label' : "publié l'article"
    })
    }}

    <input type="submit" class="btn btn-primary mt-3" value="modifier">

    {{ form_end(formArticle) }}


{% endblock %}

templates/article/nouveau.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nouvel article
{% endblock %}

{% block body %}
    <h1 class="mb-3">Creation d'un nouvel article</h1>
    {{ form_start(formArticle) }}
    {# {{ form_label(formArticle.titre, "Titre de l'article",{
        'label_attr': {'class': 'text-danger'}
    }) }}
    {{ form_widget(formArticle.titre,{ 'attr' : {'placeholder' : "veuillez saisir un titre"}}) }}
    {{ form_help(formArticle.titre,{
        'help':"Le titre doit contenir 5 caractere"
    }) }}
    #}
    {{ form_row(formArticle.titre,{
        'label' : "Titre de l'article" ,
        'attr' :{'placeholder' : "Veuillez saisir le titre de l'article"

        },
        'help' : "Le titre doit contenir 5 caractères pour etre validé"
    }) }}

    {{ form_label(formArticle.contenu , "Contenu de l'article") }}
    {{ form_widget(formArticle.contenu,{'attr':{"placeholder" :"veullez saisir le contenu de l'article"}}) }}

    {{ form_row(formArticle.categorie) }}
    {{ form_row(formArticle.isPublie ,{ 'label' : "Publier l'article ?"} ) }}

    <input type="submit" class="btn btn-primary" value="ajouter">
    {{ form_end(formArticle) }}

{% endblock %}